#development-----------------------------
# services:
#   backend:
#     build: ./server
#     container_name: backend_service
#     ports:
#       - "5000:5000"
#     environment:
#       - MONGO_URI=mongodb://mongo:27017/quick-commerce-db
#       - JWT_SECRET=this-is-a-super-secret-key-change-it
#       - PORT=5000
#     depends_on:
#       - mongo
  
#   mongo:
#     image: mongo:latest
#     container_name: mongo_db
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db

#   frontend:
#     build: ./client
#     container_name: frontend_service
#     ports:
#       - "3000:80"
#     depends_on:
#       - backend

# volumes:
#   mongo-data:



# Production-----------------------------
services:
  backend:
    build: ./server
    container_name: backend_service
    environment:
      - MONGO_URI=mongodb://mongo:27017/quick-commerce-db
      - JWT_SECRET=this-is-a-super-secret-key
      - PORT=5000
    depends_on:
      - mongo
  
  mongo:
    image: mongo:latest
    container_name: mongo_db
    volumes:
      - mongo-data:/data/db

  frontend:
    build: ./client
    container_name: frontend_service
    depends_on:
      - backend

volumes:
  mongo-data: