services:
  backend:
    build: ./server
    container_name: backend_service
    environment:
      - MONGO_URI=mongodb://mongo:27017/quick-commerce-db
      - JWT_SECRET=super-secret-key
      - PORT=5000
    depends_on:
      - mongo
  
  mongo:
    image: mongo:latest
    container_name: mongo_db
    volumes:
      - mongo-data:/data/db

  frontend:
    build: ./client
    container_name: frontend_service
    depends_on:
      - backend

volumes:
  mongo-data:
